/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness/readiness probe */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/capabilities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Model capabilities, tools and limits for the UI */
    get: operations['getCapabilities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metrics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Aggregated, content-free service metrics for operations
     * @description Requires `Authorization: Bearer <OPS_TOKEN>` when the server sets `OPS_TOKEN`.
     */
    get: operations['getMetrics'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chat/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate an assistant response as a Server-Sent Events stream
     * @description Runs the pipeline: validation → context assembly → model routing → safety checks →
     *     tools (web search, calculator, unit conversion, date/time, data processing) → streaming.
     *     Regeneration and editing the latest message are expressed by resending the
     *     conversation with the latest assistant message removed / the latest user message changed.
     */
    post: operations['streamChat'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload a document or image for analysis
     * @description Documents are converted to text; images are validated, stripped of metadata and
     *     downscaled. Uploads are retained for `uploads.retention_hours` (see `/capabilities`)
     *     and are only accessible with the uploading client's `X-Client-Id`.
     */
    post: operations['uploadFile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files/{file_id}': {
    parameters: {
      query?: never;
      header: {
        /** @description Anonymous browser-generated client identifier. */
        'X-Client-Id': components['parameters']['ClientId'];
      };
      path: {
        file_id: string;
      };
      cookie?: never;
    };
    /** Get uploaded file metadata */
    get: operations['getFile'];
    put?: never;
    post?: never;
    /** Delete an uploaded file */
    delete: operations['deleteFile'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/feedback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rate an assistant response (👍/👎). Re-submitting updates the rating. */
    post: operations['submitFeedback'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    Capability: 'fast' | 'reasoning' | 'vision';
    /** @enum {string} */
    CapabilityChoice: 'auto' | 'fast' | 'reasoning' | 'vision';
    ErrorDetail: {
      /**
       * @example validation_error
       * @example rate_limited
       * @example unsupported_file
       */
      code: string;
      /** @description Safe to display to the user. */
      message: string;
      request_id?: string | null;
      details?: unknown;
    };
    ErrorResponse: {
      error: components['schemas']['ErrorDetail'];
    };
    AttachmentRef: {
      file_id: string;
    };
    ChatMessage: {
      id: string;
      /** @enum {string} */
      role: 'user' | 'assistant';
      /** @default  */
      content?: string;
      attachments?: components['schemas']['AttachmentRef'][];
    };
    /** @description The full conversation; the last message must be a user message with text or attachments. */
    ChatRequest: {
      conversation_id: string;
      messages: components['schemas']['ChatMessage'][];
      /** @default auto */
      capability?: components['schemas']['CapabilityChoice'];
      /**
       * @description User explicitly requested a web search.
       * @default false
       */
      web_search?: boolean;
    };
    RoutingInfo: {
      /** @enum {string} */
      mode: 'auto' | 'manual';
      capability: components['schemas']['Capability'];
      /** @description Underlying open-source model id (informational). */
      model: string;
      reason: string;
    };
    Source: {
      /** @description Citation number used as [n] in the response text. */
      id: number;
      title: string;
      url: string;
      domain: string;
      snippet: string;
    };
    Usage: {
      prompt_tokens: number | null;
      completion_tokens: number | null;
    };
    StartEvent: {
      request_id: string;
      /** @description Server id for the assistant message (used for feedback). */
      message_id: string;
      routing: components['schemas']['RoutingInfo'];
    };
    DeltaEvent: {
      text: string;
    };
    ToolCallEvent: {
      id: string;
      /**
       * @example web_search
       * @example calculator
       * @example unit_convert
       * @example datetime
       * @example data_process
       */
      name: string;
      label: string;
      input: {
        [key: string]: unknown;
      };
    };
    ToolResultEvent: {
      id: string;
      name: string;
      /** @enum {string} */
      status: 'success' | 'error' | 'blocked';
      summary: string;
      duration_ms: number;
    };
    SourcesEvent: {
      sources: components['schemas']['Source'][];
    };
    SafetyEvent: {
      /** @enum {string} */
      action: 'allow_with_guidance' | 'block';
      category: string;
      message: string;
    };
    ErrorEvent: {
      code: string;
      /** @description Friendly message; no infrastructure details. */
      message: string;
      retryable: boolean;
    };
    DoneEvent: {
      /** @enum {string} */
      finish_reason: 'stop' | 'length' | 'blocked' | 'error';
      usage: components['schemas']['Usage'];
      /** @description Time to first visible output. */
      ttft_ms: number | null;
      duration_ms: number;
    };
    FileMeta: {
      id: string;
      filename: string;
      /** @enum {string} */
      kind: 'document' | 'image';
      content_type: string;
      size_bytes: number;
      /** @description Extracted text length (0 for images). */
      char_count: number;
      page_count: number | null;
      truncated: boolean;
      width: number | null;
      height: number | null;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      expires_at: string;
    };
    FeedbackRequest: {
      conversation_id: string;
      message_id: string;
      /** @enum {string} */
      rating: 'up' | 'down';
      comment?: string | null;
      capability?: components['schemas']['Capability'] | null;
      model?: string | null;
    };
    FeedbackResponse: {
      id: string;
      message_id: string;
      /** @enum {string} */
      rating: 'up' | 'down';
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    HealthResponse: {
      /** @enum {string} */
      status: 'ok' | 'degraded';
      version: string;
      environment: string;
      /** @enum {string} */
      database: 'ok' | 'unavailable';
      llm_provider: string;
      search_provider: string;
    };
    CapabilityInfo: {
      id: components['schemas']['Capability'];
      label: string;
      description: string;
      supports_images: boolean;
    };
    ToolInfo: {
      name: string;
      label: string;
      description: string;
    };
    UploadLimits: {
      max_bytes: number;
      max_files_per_message: number;
      document_extensions: string[];
      image_extensions: string[];
      retention_hours: number;
    };
    ChatLimits: {
      max_message_chars: number;
      max_messages: number;
    };
    CapabilitiesResponse: {
      default: components['schemas']['CapabilityChoice'];
      capabilities: components['schemas']['CapabilityInfo'][];
      tools: components['schemas']['ToolInfo'][];
      uploads: components['schemas']['UploadLimits'];
      chat: components['schemas']['ChatLimits'];
    };
    Percentiles: {
      p50: number | null;
      p95: number | null;
      max: number | null;
    };
    MetricsResponse: {
      window_minutes: number;
      /** Format: date-time */
      since: string;
      total_requests: number;
      by_status: {
        [key: string]: number;
      };
      by_capability: {
        [key: string]: number;
      };
      errors_by_code: {
        [key: string]: number;
      };
      tool_usage: {
        [key: string]: number;
      };
      error_rate: number;
      total_retries: number;
      ttft_ms: components['schemas']['Percentiles'];
      duration_ms: components['schemas']['Percentiles'];
      feedback: {
        [key: string]: number;
      };
    };
  };
  responses: {
    /** @description Error with a user-safe message */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
  };
  parameters: {
    /** @description Anonymous browser-generated client identifier. */
    ClientId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
      /** @description Database unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  getCapabilities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Capabilities */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CapabilitiesResponse'];
        };
      };
    };
  };
  getMetrics: {
    parameters: {
      query?: {
        window_minutes?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Metrics summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MetricsResponse'];
        };
      };
      401: components['responses']['Error'];
    };
  };
  streamChat: {
    parameters: {
      query?: never;
      header: {
        /** @description Anonymous browser-generated client identifier. */
        'X-Client-Id': components['parameters']['ClientId'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatRequest'];
      };
    };
    responses: {
      /** @description Stream of chat events (see the event table in the API description). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': string;
        };
      };
      422: components['responses']['Error'];
      429: components['responses']['Error'];
    };
  };
  uploadFile: {
    parameters: {
      query?: never;
      header: {
        /** @description Anonymous browser-generated client identifier. */
        'X-Client-Id': components['parameters']['ClientId'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description File processed */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FileMeta'];
        };
      };
      413: components['responses']['Error'];
      415: components['responses']['Error'];
      422: components['responses']['Error'];
      429: components['responses']['Error'];
    };
  };
  getFile: {
    parameters: {
      query?: never;
      header: {
        /** @description Anonymous browser-generated client identifier. */
        'X-Client-Id': components['parameters']['ClientId'];
      };
      path: {
        file_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File metadata */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FileMeta'];
        };
      };
      404: components['responses']['Error'];
    };
  };
  deleteFile: {
    parameters: {
      query?: never;
      header: {
        /** @description Anonymous browser-generated client identifier. */
        'X-Client-Id': components['parameters']['ClientId'];
      };
      path: {
        file_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components['responses']['Error'];
    };
  };
  submitFeedback: {
    parameters: {
      query?: never;
      header: {
        /** @description Anonymous browser-generated client identifier. */
        'X-Client-Id': components['parameters']['ClientId'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FeedbackRequest'];
      };
    };
    responses: {
      /** @description Existing rating updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FeedbackResponse'];
        };
      };
      /** @description Feedback recorded */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FeedbackResponse'];
        };
      };
      422: components['responses']['Error'];
    };
  };
}
