"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 19:47:44.239694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('routing_mode', sa.String(length=8), nullable=False),
    sa.Column('capability', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('route_reason', sa.String(length=255), nullable=False),
    sa.Column('tools_used', sa.JSON(), nullable=False),
    sa.Column('search_used', sa.Boolean(), nullable=False),
    sa.Column('safety_action', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('ttft_ms', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_requests'))
    )
    with op.batch_alter_table('chat_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_requests_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_chat_requests_created_status', ['created_at', 'status'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('capability', sa.String(length=16), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('client_id', 'message_id', name='uq_feedback_client_message')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_client_id'), ['client_id'], unique=False)

    op.create_table('uploaded_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_files'))
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_files_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_expires_at'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_client_id'))

    op.drop_table('uploaded_files')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_client_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('chat_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_requests_created_status')
        batch_op.drop_index(batch_op.f('ix_chat_requests_client_id'))

    op.drop_table('chat_requests')
    # ### end Alembic commands ###
